name: CI

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workflow-lint:
    uses: kellen-miller/ci/.github/workflows/gh-actions-lint.yaml@f4096214828c04a170d62e79f7b3eab035364522

  lint:
    uses: kellen-miller/ci/.github/workflows/node-lint.yaml@f4096214828c04a170d62e79f7b3eab035364522
    with:
      format-script: format:check

  build-and-test:
    uses: kellen-miller/ci/.github/workflows/node-test.yaml@f4096214828c04a170d62e79f7b3eab035364522
    with:
      test-script: test:ci
      install-playwright: true
      playwright-browsers: chromium
      artifact-name: playwright-report
      artifact-path: |
        playwright-report/
        test-results/
